### ISSUE TITLE
There is no option to select the site version (mobile)

### ISSUE THREAD

**Issue by LilkitFutDev** [Utradea-Inc/utradea-public#224] opened 2021-04-27 16:40 UTC
**Bug   Name:** | There is no option to select the site   version (mobile) 
**Area Path:** | https://beta.utradea.com/
**Severity:** | low 
**Reported By:** | Yarov 

**Description:** | There is no option to select the site version (the   selection page appears but then immediately switches to the mobile version)  

**Steps To Reproduce:** 
1 | Go to https://beta.utradea.com/ (mobile) 
2 | Pay attention to the main screen 

**Expected Result:** | Page with site version selection
**Actual result:** | The selection page appears but then immediately   switches to the mobile version

**Attachment:** | https://www.dropbox.com/s/guddm3v7m9w3ilj/20210427_193512.mp4?dl=0 

**Chrome version:** | 90.0.4430.82 (mobile)

**Comment by zhan1634** [comment] 2021-04-27 22:41
This is not a bug, but there is a slight latency in loading the right website. This will be fixed when we update our servers next month to handle the redirect at the server level.

**Closed as completed by zhan1634** 2021-04-27 22:41 UTC
