### ISSUE TITLE
Unable to use the account settings page

### ISSUE THREAD

**Issue by LilkitFutDev** [Utradea-Inc/utradea-public#223] opened 2021-04-27 15:59 UTC
**Bug   Name:** | Unable to use the account settings page 
  
**Area Path:** | https://beta.utradea.com/settings 
**Severity:** | High
**Reported By:** | Yarov 

**Description:** | After clicking on the sign with the account   settings, the page opens but after a few seconds becomes unavailable 

**Steps To Reproduce:**
1 | Go to https://beta.utradea.com/ 
2 | Click on the "Profile" button in the left menu
3 | Click on the "Setting" button 
4 | Pay attention to the main screen 

**Expected Result:** | The account settings page opens successfully
**Actual result:** | After clicking on the sign with the account   settings, the page opens but after a few seconds becomes unavailable

**Attachment:** | https://www.dropbox.com/s/ahyzx6j998g6kk0/bandicam%202021-04-27%2018-55-08-055.mp4?dl=0   

**Chrome version:** | 90.0.4430.93 
**Firefox version:** | 88

**Comment by zhan1634** [comment] 2021-04-27 23:27
Duplicate of #215

**Closed as completed by zhan1634** 2021-04-27 23:27 UTC
