### ISSUE TITLE
After logging out and again login page still open in post idea section instead of homepage

### ISSUE THREAD

**Issue by Ashish8822** [Utradea-Inc/utradea-public#98] opened 2021-03-04 08:36 UTC
When user is in the post an idea section and from there he logout after few minute he log in again. He goes to the same post an idea section. It should take user to the homepage as a new session is being created after logging out and getting logged back in again. 

Steps :
1. Go to https://beta.utradea.com/
2. Login with your credentials
3. Navigate to post an idea section
4. Log-out from there 
5. Log-in again
6. Observe

Screen recording :  http://somup.com/crefjTDsM7
Note : Tested on Chrome , Firefox , Edge . Cookies and Cache clear

**Comment by zhan1634** [comment] 2021-03-04 14:10
Duplicate of bug #13 - again this is kept the same because there's another feature in the site where if someone shares a link to a position or a specific page, but is not logged in - the system will automatically log them out but keep the same session alive so when they do create an account they come back and see what they were supposed to see. This is not a bug and should be kept. In 90% of the scenarios when someone logs out they will not log back in in the same session.

**Closed as completed by zhan1634** 2021-03-04 14:10 UTC
